const fs = require('fs');
const readline = require('readline');
const { google } = require('googleapis');
const path = require('path');
require('dotenv').config();

// 설정 파일 로드
const configPath = path.join(__dirname, 'config.json');
const config = fs.existsSync(configPath) ? JSON.parse(fs.readFileSync(configPath, 'utf8')) : {};

const SCOPES = ['https://www.googleapis.com/auth/youtube.upload'];
const TOKEN_PATH = path.join(__dirname, 'token.json');

/**
 * YouTube 업로드를 위한 OAuth2 클라이언트 생성
 */
function getOAuth2Client() {
    const client_id = process.env.GOOGLE_CLIENT_ID;
    const client_secret = process.env.GOOGLE_CLIENT_SECRET;
    const redirect_uri = 'http://localhost:5679';

    if (!client_id || !client_secret) {
        throw new Error('Google OAuth credentials not found in .env');
    }

    return new google.auth.OAuth2(client_id, client_secret, redirect_uri);
}

/**
 * 비디오 업로드 함수
 */
async function uploadToYouTube({ videoPath, title, description, categoryId = '25' }) {
    console.log("--- YouTube Video Upload Starting ---");

    const auth = getOAuth2Client();

    if (!fs.existsSync(TOKEN_PATH)) {
        throw new Error('OAuth token not found. Please run authentication first.');
    }

    const token = fs.readFileSync(TOKEN_PATH);
    auth.setCredentials(JSON.parse(token));

    const youtube = google.youtube({ version: 'v3', auth });

    if (!fs.existsSync(videoPath)) {
        throw new Error(`Video file not found: ${videoPath}`);
    }

    const res = await youtube.videos.insert({
        part: 'snippet,status',
        requestBody: {
            snippet: {
                title: title || 'AI News Briefing',
                description: description || 'Generated by AI',
                categoryId: categoryId || config.youtube?.defaultCategory || '25',
            },
            status: {
                privacyStatus: config.youtube?.privacyStatus || 'unlisted',
            },
        },
        media: {
            body: fs.createReadStream(videoPath),
        },
    }, {
        onUploadProgress: evt => {
            const progress = (evt.bytesRead / fs.statSync(videoPath).size) * 100;
            if (process.stdout.isTTY) {
                readline.clearLine(process.stdout, 0);
                readline.cursorTo(process.stdout, 0, null);
                process.stdout.write(`Upload Progress: ${Math.round(progress)}%`);
            }
        },
    });

    console.log('\n--- Success! Video Uploaded ---');
    console.log('Video ID:', res.data.id);
    console.log('URL: https://www.youtube.com/watch?v=' + res.data.id);

    return res.data;
}

module.exports = { uploadToYouTube, getOAuth2Client };

// CLI 실행 처리
if (require.main === module) {
    (async () => {
        try {
            const scriptPath = path.join(__dirname, 'news_script.json');
            let videoTitle = 'AI 뉴스 브리핑';
            let videoDesc = 'AI가 수집하고 생성한 최신 뉴스 브리핑입니다.';

            if (fs.existsSync(scriptPath)) {
                const scriptData = JSON.parse(fs.readFileSync(scriptPath, 'utf8'));
                videoTitle = `[AI 뉴스] ${scriptData.summary.substring(0, 50)}...`;
                videoDesc = scriptData.summary;
            }

            const videoPath = path.join(__dirname, 'videos', 'final_video.mp4');
            await uploadToYouTube({
                videoPath,
                title: videoTitle,
                description: videoDesc
            });
        } catch (err) {
            console.error('Upload failed:', err.message);
            process.exit(1);
        }
    })();
}
